[config]
schemaVersion = "0.2.1"

[package]
namespace = "Binbin"
name = "Drogg_The_Yeti"
versionNumber = "0.2.1"
description = "New Hero Mod for Drogg, the Yeti. A mage that specializes in Bludgeoning foes with Chill and Cold Spells."
websiteUrl = "https://github.com/binbinmods/Drogg"
containsNsfwContent = false

[package.dependencies]
meds-Obeliskial_Essentials = "1.5.1"
meds-Obeliskial_Content = "1.5.6"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./Drogg"
target = ""


[publish]
repository = "https://thunderstore.io"
communities = [ "across-the-obelisk", ]
[publish.categories]
across-the-obelisk = [ "mods", ]


